kairos:
  dns: false
k3s:
  enabled: false
stages:
  initramfs:
    - name: "Setup hostname"
      hostname: "dns"
    - name: "Setup users"
      users:
        c3os:
          passwd: "Asdf1234"
      authorized_keys:
        c3os:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9B6zMB/ycG9cMfWtwIT/9mWaNGv7nu+h5nrHJ4drkl shika@pop-os"
    - name: "Create DNS server config"
      commands:
        - "wget https://github.com/0xERR0R/blocky/releases/download/v0.20/blocky_0.20_Linux_arm64.tar.gz -q -O - | tar -xzvf - -O blocky > /usr/local/blocky"
      files:
        - path: /etc/blocky-config.yaml
          content: |
            upstream:
              default:
                - tcp-tls:dot.libredns.gr:853
                - https://doh.libredns.gr/dns-query
                - https://fi.doh.dns.snopyta.org/dns-query
                - tcp-tls:fi.dot.dns.snopyta.org
            blocking:
              blackLists:
                ads:
                  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
                  - https://dbl.oisd.nl/
                  - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
                  - https://raw.githubusercontent.com/hufilter/hufilter/master/hufilter-dns.txt
              clientGroupsBlock:
                default:
                  - ads
            customDNS:
              rewrite:
                home: local
                lan: local
              mapping:
                openwrt.local: 192.168.1.1
                picloud.local: 192.168.1.10
                dns.local: 192.168.1.20
            port: 53
            httpPort: 80
            logLevel: error
            logFormat: json
            logPrivacy: true
            prometheus:
              enable: true
              path: /metrics
          permissions: 0777
    - name: "Create and start blocky service"
      files:
        - path: /etc/openrc/conf.d/blocky
          content: |
            #!/sbin/openrc-run

            depend() {
                need net
            }

            command="/usr/local/blocky"
            command_args="--config /etc/blocky-config.yaml"
            command_user="c3os:c3os"
            pidfile="/run/${RC_SVCNAME}/pid"
      systemctl:
        enable:
          - blocky
        start:
          - blocky
