kairos:
  dns: false
k3s:
  enabled: true
stages:
  initramfs:
    - name: "Setup hostname"
      hostname: "picloud"
    - name: "Setup users"
      users:
        c3os:
          passwd: "Asdf1234"
      authorized_keys:
        c3os:
          - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9B6zMB/ycG9cMfWtwIT/9mWaNGv7nu+h5nrHJ4drkl shika@pop-os"
